name: Test Site Build
on: [push]

jobs:
  build_nuget:
    name: Build Node App
    runs-on: ubuntu-latest
    steps:
    - name: setup-dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
      
    - name: checkout-repo
      uses: actions/checkout@v2
      with:
        clean: 'true'

    - name: print-directory 
      run: ls -la

  build_dotnet:
    name: Build DotnetCore app
    runs-on: ubuntu-latest
    needs: build_nuget
    steps:
    - name: print-greeting
      env:
        MY_VAR: Hi there! My name is
        FOO: dotnet bar
      run: |
        echo $MY_VAR $FOO.
    - name: print-directory
      run: |
        ls -la
    


